### ISSUE TITLE
Keep an existing UTCTiming element, option "/utc_keep/"

### ISSUE THREAD

**Issue by Murmur** [Dash-Industry-Forum/livesim2#138]
Add url option `/utc_keep/` to not drop and touch an existing UTCTiming element in a source manifest. This would give an easy enough configuration case-by-case and worked in a strictly closed firewalled test environments.
`<UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-iso:2014" value="https://my.private.system/utctiming.php"/>`

Current `/utc_none/` option drops UTCTiming field from the manifest and probably is best work like that.

**Comment by tobbee** [comment]
Sounds like a good approach to be able to set up any UTCTiming if you have your own content.

**Comment by tobbee** [comment]
@Murmur Please have a look at PR #139

**Comment by Murmur** [comment]
@tobbee Tested this PR change on our server and works ok, please merge to a `master` trunk.
`https://nginx.dev/livesim2/tsbd_240/mup_4/spd_8/utc_keep/00_llama_h264_v9/manifest_1080p.mpd`
`<UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-iso:2014" value="https://nginx.dev/videos/utctiming.php"></UTCTiming>`

**Comment by tobbee** [comment]
I merged the `utc_keep` PR. Regarding the UTCTiming, the `?isoms` is the new thing that Daniel Silhavy said he wanted to use. I agree that a simple number looks less like an iSO timestamp. Maybe Daniel has some more insight? May be worth bringing up in another discussion thread.

**Comment by Murmur** [comment]
LiveSim2 should give two options for `urn:mpeg:dash:utc:http-iso:2014` and `urn:mpeg:dash:utc:http-xsdate:2014` variants:
* https://time.akamai.com/?iso -> 2023-11-17T13:49:55Z
* https://time.akamai.com/?iso&ms -> 2023-11-17T13:49:55.743Z

Accordingly `/utc_httpxsdate/ | /utc_httpxsdatems/` and `/utc_isodate/ | /utc_isodatems/`

**Comment by tobbee** [comment]
@Murmur Good to get this clarified, but I think you shouldn't hijack one issue to discuss a to another. It is much clearer to start a new one.
