### ISSUE TITLE
Parsing UTC timing response fails

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/livesim2#147]
The `UTCTiming` element in the livesim2 streams currently points to this URL: https://time.akamai.com/?ms. It uses a `schemeIdUri` set to `urn:mpeg:dash:utc:http-xsdate:2014`.

This combination leads to parsing errors in dash.js and the Shaka player. I think the correct URL for the `schmeIdUri` defined above is this one: https://time.akamai.com/?iso&ms

Example MPD: https://livesim2.dashif.org/livesim2/testpic_2s/Manifest.mpd

**Comment by tobbee** [comment]
I thought I had fixed that, but apparently I used the wrong combination.

The one you describe is in
https://github.com/Dash-Industry-Forum/livesim2/blob/38da4dbae18b72777a782880b6e3127c71827d49/cmd/livesim2/app/configurl.go#L52

It would be good if there was a proper list of definitions somewhere.

**Comment by tobbee** [comment]
Reading the specs, I cannot see that there is any real difference between the xsdate and iso formats, so I will
make them both point to the `?iso` URL variants.

**Comment by tobbee** [comment]
The fix in #148 has been merged into v1.1.1 and published on https://livesim2.dashif.org
