### ISSUE TITLE
Implement MPD Patch

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#155]
MPD Patch allows for asking for difference of an MPD compared to a previous MPD version defined by publishTime.

It is specified using an algorithm using XPath defined in

https://datatracker.ietf.org/doc/html/rfc5261

To implement this, one would need to 

1) Be able to retrieve/construct an MPD based on publishTime as a reference
2) Be able to calculate the difference

For step 1), caching of segments would be useful, but is currently not part of livesim2.
Just using publishTime as nowMS input would probably work as well.

It may also be possible to do this whole thing as a caching proxy.
That should probably be another service and may need a better XML engine.

**Comment by haudiobe** [comment]
Test Call March 26, 2024
- MPD patch is supported in dash.js, but no tests
- Hulu is deploying it
- would be good to get this done
