### ISSUE TITLE
Wrong `<ProgramInformation>` when configured for SegmentTimeline with $Time

### ISSUE THREAD

**Issue by bwallberg** [Dash-Industry-Forum/livesim2#160]
**Is**
```
<ProgramInformation>
    <Title>640x360@30fps, 48kHz audio at 48kbps, SegmentTemplate with $Number$</Title>
</ProgramInformation>
```

**Expected**
```
<ProgramInformation>
    <Title>640x360@30fps, 48kHz audio at 48kbps, SegmentTemplate with $Time$</Title>
</ProgramInformation>
```

**Comment by tobbee** [comment]
@bwallberg 

Interesting observation. The current ProgramInformation is verbatim from the VoD source and sometimes does not have only a Title element but also a Source. It may also be absent. It typically doesn't tell things like the type of segment addressing, but in this case it is part of https://github.com/dash-Industry-Forum/livesim-content where I have added that information.

I don't think it is a good idea to override this information in general, but the standard allows multiple ProgramInformation elements, so I think it makes sense to add another ProgramInformation element that describes the Livesim2 settings more verbosely than the URL itself. I'll suggest that I make another Issue with a proposal for an enhancement in that direction and close this one. Do you think that is OK?

**Comment by tobbee** [comment]
As a fix, I am removing the details about the Segment Addressing type from  https://github.com/dash-Industry-Forum/livesim-content and will update the content at https://livesim2.dashif.org. Then there will be no misleading information. I'm also adding a Source element to point to the livesim-content source.

An extra ProgramInformation entry may still be interesting, but this particular "misinformation" will be gone before such a feature is implemented.

**Comment by tobbee** [comment]
I've changed the content now, so the ProgramInformation for an asset like https://livesim2.dashif.org/vod/testpic_2s/Manifest.mpd looks like:

```
<ProgramInformation moreInformationURL="https://github.com/dash-Industry-Forum/livesim-content">
      <Title>Basic MPD with 640x480@30 video at 300kbp and 48kbps audio</Title>
      <Source>VoD source for DASH-IF livesim2</Source>
</ProgramInformation>
 ```

**Comment by tobbee** [comment]
I've made an entry for a potential task at https://github.com/orgs/Dash-Industry-Forum/projects/7?pane=issue&itemId=53495413
and consider this issue closed.

**Comment by bwallberg** [comment]
🙌
