### ISSUE TITLE
Support HbbTV pre-encrypted content that works with livesim1

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#219]
Something in livesim2 prohibits the looping of some pre-encrypted HbbTV test content that works with livesim1.

This issue is about making the necessary changes to livesim2 in order to make that content work.
Some minimal changes may also be needed on the content.

This may include things like:

1. Making a more transparent MPD processing with a SAX XML parser
2. Check and possibly improve the handling of encrypted audio segments

See #213 for a case where pre-encrypted Widevine video was made to work by tuning the packager.

**Comment by Murmur** [comment]
If you need test content(zipped assets data) feel free to contact me.

**Livesim2: NoDRM**
https://refapp.hbbtv.org/livesim2/tsbd_240/mup_4/spd_8/utc_keep/00_llama_h264_v9/manifest_1080p.mpd

**Livesim1: DRM CENC widevine** laUrl works few few weeks.
https://refapp.hbbtv.org/livesim/mup_4/spd_8/00_llama_h264_v9_8s_cenc/manifest_baseurl_wv.mpd
https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BwAAABc2KeEAJDY2NzY5OWMwLTViODYtNDMwOS1iMjA4LTRlY2JkMjdmMWNmOAAAAIC7eetKNLrt0kWI-1g6u46WqQO13UEUkHevGFyrWZgfOYoPqWTl_d7A3qn7T1XpfADcozqapYVkHYwVekuq56wND7Sl35MlUFe4ecVKIHU5vjzoczEpth9-q-bIc1vrWZNfoQbBKBxy3Q1jXib_CbukzBiQv3HxYmFezmal6JCiawF3LH4Ptqg6iG38rTNCaAnAuLKM

**Livesim1: DRM CBCS widevine** laUrl works few few weeks.
https://refapp.hbbtv.org/livesim/mup_4/spd_8/00_llama_h264_v9_8s_cbcs/manifest_baseurl_wv.mpd
https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BwAAABc2KfcAJDY2NzY5OWMwLTViODYtNDMwOS1iMjA4LTRlY2JkMjdmMWNmOAAAAIDO1fImL3H2sAcEsPbaJ7lvHKsudYA2crFN_RqG9_eMl5Veynbrosm-HsP_Cv_2Gvt8veUp2rt-2iGK45Kqx-1riTiiCn9fhfNRKDyGFk9qq_KCkyh8hpXXQMaMIKFRlXuBNvcHWu8NDIy0W8shSYGVNfNPZ6HhMIYmEMb0P9CrBnnyJ9Jwth-GoDCiNyqRIaLO96rr

---

This does not work, it's an init segment `404NotFound` reply.

**Livesim2: DRM CENC widevine** laUrl works few few weeks.
https://refapp.hbbtv.org/livesim2/tsbd_240/mup_4/spd_8/utc_keep/00_llama_h264_v9_cenc/manifest_wvcenc_1080p.mpd
https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BwAAABc2KeEAJDY2NzY5OWMwLTViODYtNDMwOS1iMjA4LTRlY2JkMjdmMWNmOAAAAIC7eetKNLrt0kWI-1g6u46WqQO13UEUkHevGFyrWZgfOYoPqWTl_d7A3qn7T1XpfADcozqapYVkHYwVekuq56wND7Sl35MlUFe4ecVKIHU5vjzoczEpth9-q-bIc1vrWZNfoQbBKBxy3Q1jXib_CbukzBiQv3HxYmFezmal6JCiawF3LH4Ptqg6iG38rTNCaAnAuLKM

**Comment by tobbee** [comment]
I looked a little at loading  https://refapp.hbbtv.org/videos/00_llama_h264_v9/cenc/manifest_wvcenc_1080p.mpd into livesim2. As far as I can tell, the MPD and init segments look fine and I managed to fetch all the init segments.

When it comes to the video and audio segments, there are problems though.

One particular issue with them is that they all have two fragments which are independently encrypted. That complexity may contribute to the error I see when analysing the first output segment, number 0, by specifying:

```sh
curl -O http://localhost:8888/livesim2/hbbtv/v1/0.m4s\?nowMS\=10000
mp4ff-info 0.m4s
```

results in the result `offset from saio (730) relative moof start differs from senc data start 726`.
I cannot guarantee it, but segments with a single fragment may work better.

It should of course be possible to support this type of segments, but I don't know when I will get time to look into it.

**Comment by Murmur** [comment]
@tobbee thanks, we do indeed use a multi moof+mdat(2..N) structure in a test material to see clients support it properly.

I create a separate test with the same settings but just one moof+mdat pair and let you know.

**Comment by tobbee** [comment]
@Murmur I'm spending some time on this right now. I'm not finished but have a draft PR #221 that should do better logging and checking of pre-encrypted content when loading it and do minimal changes to the segments when adapting them to the live flow. This includes support of your example content with two fragments per segment.

An issue I found when downloading your  asset https://refapp.hbbtv.org/videos/00_llama_h264_v9/cenc/manifest_wvcenc_1080p.mpd
is that the audio representations have 7 segments while the video has 13.

I've added checks for this and refuse to load such pre-encrypted assets. I haven't tested it yet, but reducing the numbers of video segments to 7 should make the asset accepted and the segments should go through the system and look fine downstream.

**Comment by Murmur** [comment]
>>https://refapp.hbbtv.org/videos/00_llama_h264_v9/cenc/manifest_wvcenc_1080p.mpd
>>is that the audio representations have 7 segments while the video has 13.

@tobbee Content has 100 segments for all video and audio tracks, no idea what is a 7/13 segment count.
```
duration=PT0H6M24.000S (384sec)
videoseg: dur="49152" /  timescale="12800" = 3.84s, startNumber="1"
audioseg: dur="184320" / timescale="48000" = 3.84s, startNumber="1" 
files: $RepID$/i_wvcenc.mp4 and $RepID$/1..100.m4s
```

**Comment by tobbee** [comment]
@Murmur I downloaded the segments with a tool, so maybe I didn't get all of them.

For adding Marlin, I need to add some extra stuff to the `dash-mpd` library, but it should be simple.

Regarding using the MPD duration for restricting the number of segments, I'm not sure that works, but you can check yourself. The most reliable way should be to make sure that all segments have the same duration.

**Comment by Murmur** [comment]
Yes a tool failed to download all segment files, all files are `segdur=3.84s`  fully aligned.

Limiting a manifest duration is to skip the last vod segment(100.m4s) `Brand: msdh, compBrand: msdh, msix, lmsg | lmsg=last Media Segment indicator for ISO base media file format` and just rotate 1-99.m4s `Brand: msdh, compBrand: msdh, msix` segments.

I need to double check if Livesim2 still serves 100.m4s file even if manifest@duration did not go that far, we may not want that(lmsg) be sent in 24h/7d live streaming. 
My intuition was Livesim2 oboyes a vod duration and rotates only that time window.

**Comment by tobbee** [comment]
@Murmur I checked the [dash-mpd ](https://github.com/Eyevinn/dash-mpd )code, and it should already support Marlin namespace. As usual, it will move the namespace prefix into an element instead of listing at the top, though. The schemeIdUri is pass-through, but I just changed the constant in the package and added a small test based on your content in https://github.com/Eyevinn/dash-mpd/pull/33

In any case, I think that Marlin should work, unless there is some limitation in the XML parser in the player that does require the XML namespace prefix to be defined in the top element.

The other general change in dash-mpd is that durations will be simplified to remove heading or trailing zeros like `PT0H2.500S` will be changed into `PT2.5S`.

Regarding "limiting the asset using mediaPresentationDuration in the MPD", it does currently not work. For SegmentTemplate with Number, the loader loads consecutive numbers until there is an error. The only way to stop that is to add an `endNumber` attribute in the SegmentTemplate. I just checked that, and it works.

**Comment by tobbee** [comment]
@murmur I close this for now. If there are some new issues turning up, you can open a new issue, or reopen this if the overlap is great.

**Comment by Murmur** [comment]
Thanks for everything. My pre-encoded drm content works, but need to run an extensive tests on multiple HbbTVs. PC browsers work so it's always a good base. This is a very good feature to use them as-is much as possible, I prefer this drm method to have a freedom provide different kind of mp4 packaging structures.

Win10: Edge-Playready(cenc, cbcs), Edge-Widevine(cenc, cbcs), Firefox-Widevine(cenc, cbcs), Chrome-Widevine(cenc, cbcs), all use H264+AAC codecs.

**Comment by tobbee** [comment]
OK. Great that it works for you.

livesim2 is based on representations which each have one init segment, so you can have different manifests which use different representations in the same "asset directory".  Init segment variations inside the same representation is nothing I've thought about.

My understanding is that the recommendation is to not have any DRM-specific information in the init segments, but keep PSSH boxes etc in the MPD. If you do it like that and have a common init segment. Alternatively, you should be able to put multiple PSSH boxes inside a common init segment. 

In any case, good that you found a way that works of you. If you can use symbolic links between your different directories, you can at least save on the copies of segments.

**Comment by Murmur** [comment]
We have a test content with an idea it does not signal "any extra DRMs" to make sure HbbTV native player does not pick up something we do not want to test. So run a manifest with playready xml only and init with with playready ssh only. 

True, init segment could go without the playready,widevine+other PSSH boxes. Test content is still using the traditional guidelines where PSSH box was still a thing.
