### ISSUE TITLE
Minimal processing of pre-encrypted content

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#220]
Pre-encrypted content should not be re-fragmented but instead the segments should be kept as close to the original as possible. This includes

1. Better checks and logging when loading pre-encrypted content. For example that all encrypted tracks have the same duration.
2. Avoid and refragmentation of encrypted segments and only update baseMediaDecodeTime, sequenceNumber and sidx box earliestPresentationTime

The content from #219 can be used as test source.

**Comment by Murmur** [comment]
I wish we had an url option or something else for non-encrypted content, just do a minimal set of changes. Do not try to remux the entire file. Possible for nonencrypted test assets as well?

**Comment by tobbee** [comment]
Solved by #221.
