### ISSUE TITLE
Add automatic certificates using ACME

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#24]
The current HTTPS support requires that a valid key and certificate is available. This requires manual work and there is a risk that the certificate is not updated as it expires.

It would therefore be beneficial to have automatic certificate installation and renewal using the ACME protocol towards Let's Encrypt as an option.

A possible way to achieve that would be to integrate the [certmagic](https://github.com/caddyserver/certmagic) package.

**Comment by wilaw** [comment]
+1

This feature would be very useful for anyone wanting to test DRM/EME content, for which https delivery is required. Would also simplify maintenance of the DASH IF hosted version of livesim2.

**Comment by tobbee** [comment]
Solved by #57.
