### ISSUE TITLE
Add whitelist or tokens to request limiter

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#48]
Limiting the number of requests per 24hours may be too restrictive for tests of dash.js and other tools.
A whitelist of IP-addresses that can get more requests may therefore be needed if a common server should be used for testing.

Another possibility would be to have a token for specific test systems such as dash.js.
Such a token would then need to go into every request to be most efficient.
Generation/verfications of such tokens add a bit to the complexity of the setup, but may be worth the effort.

Another possibility may be to make the full test setup automatic.

**Comment by dsilhavy** [comment]
I can confirm that the previous limit (1000 requests) was reached quickly on my side. I am using the Livesim streams for various tests, including

- Local development
- Running Karma based functional tests to check for regression
- Running functional tests via CircleCI and Browserstack automatically for each pull request 

IP whitelisting for browserstack seems to be possible but might cost extra:https://www.browserstack.com/local-testing/inbound-ip-whitelisting. A token seems like a suitable option, we can add that as a secret on Github or CircleCI. For local testing I can use the same token. Maybe this would also be an option to monetize the LiveSim2. Companies that require more than 1000 requests per 24h can buy a token from DASH-IF.

**Comment by tobbee** [comment]
@dsilhavy Do you have a proposal for a specific way to add the token?

The main three possibilities I see are:

1. Add a query-string `?token=xyz`
2. Add an HTTP request header `dashif-token: xyz`
3. Add an extra part in the URL `/token_xyz` (similar to what is done for sessions in livesim1)

Given that DASH-IF has guidelines for Token-Based Access Control, we may use some version of that.
The actual token is then supposed to be sent as `?dash-if-ietf-token=xyz` as far as I understand.

I'll bring up this issue in the DASH-IF IOP meeting tomorrow

**Comment by dsilhavy** [comment]
I favor option 2) adding an HTTP request header

**Comment by tobbee** [comment]
In the DASH-IF meeting on Aug. 25, it was suggested that the "Origin" request header could be used as a means to filter "allowed users". The server should then have a list of "gold origins".

**Comment by Murmur** [comment]
Yes, we as a `HbbTV ReferenceApp, test laboratoy` would need "unlimited" access if that is to be implemented.

**Comment by tobbee** [comment]
@Murmur The default when you set up the server yourself is unlimited access. The question is how interesting a token-based approach that allows some users to have unlimited access is?

In general, the intention is that it should be so easy to set up the server yourself so that people who wants to run it a lot, will do that.

**Comment by tobbee** [comment]
Having one fixed limit of 10000 requests/24h/IP address is working fine for the DASH-IF linode instance at https://livesim2.dashif.org. There is therefore currently no need for this, so I close this ticket.
