### ISSUE TITLE
Add support for SCTE-35 emsg signalling

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#69]
One of the teststreams of dash.js uses the scte35 option of livesim.
The URL is

https://livesim.dashif.org/livesim/scte35_2/testpic_2s/Manifest.mpd

On receiving such a URL, livesim does:

- Add an extra profile to the MPD : `http://dashif.org/guidelines/adin/app`
- Adds an InbandEventStream node to the video AdaptationSet `         <InbandEventStream schemeIdUri="urn:scte:scte35:2013:xml" value="999" />`
- Inserts a number of emsg messages every minute with ad duration of 10s (or 20s in some cases).

Acceptance Criteria:

- Livesim2 should generate corresponding content, but updated to follow SCTE-214-1_2022.
  - This includes using a binary format for the SCTE35 message instead of XML
- The feature should be better documented

Part of #59

**Comment by tobbee** [comment]
@dsilhavy How important is the SCTE-35 signalling for dash.js testing, and does it matter if the content changes?
The SCTE-214 spec is quite a bit different now compared to what is in livesim, incl. version of emsg box, binary instead of XML SCTE payload etc.

Except for this stream, all other URLs that are in the dash.js code works as they should. They are not available online yet, though.

**Comment by dsilhavy** [comment]
@tobbee Thanks for the updates, sounds very promising. I use the Livesim1 SCTE35 inband events stream for checking our event implementation. The payload of the events doesn't matter, what would be important is that we know the timing of the events as we do today. For instance, in this example we know that we can expect an event at 10s and 40s: https://reference.dashif.org/dash.js/nightly/samples/advanced/listening-to-SCTE-EMSG-events.html

I also used this stream to implement a functional test that checks if the event callbacks are triggered in time. The test will be part of dash.js v.5

Is it possible to provide such a stream with livesim2 if the payload is not important?

Btw we have support for v0 and v1 events in dash.js which changes the event timing accordingly. This would also be great to have, but not mandatory in my opinion.

**Comment by tobbee** [comment]
@dsilhavy Good to know that it is useful. I've implemented roughly the same functionality as in livesim, but updated to follow the SCTE spec. From your point, I think that the main difference is that the SchemeIDURI is changing to "urn:scte:scte35:2013:bin" (bin instead of xml) and that emsg is changed to version 1.

I will upload a PR later today. It should soon be at https://livesim2.dashif.org if you want to test it from there.
