### ISSUE TITLE
Add Timing-Allow-Origin header

### ISSUE THREAD

**Issue by tobbee** [Dash-Industry-Forum/livesim2#87]
dash.js 5.0 will look at detailed timing information if "Timing-Allow-Origin" header is present in the response.

More details are available at

https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/Resource_timing

It should probably be enabled by default.

**Comment by dsilhavy** [comment]
Thanks @tobbee , see changes here: https://github.com/Dash-Industry-Forum/dash.js/pull/4237
